web:
  extends:
    file: web.yml
    service: web
  environment:
    - TEST_ENV=test-value
  links:
    - database:db
  ports:
    - "2222:22"
data:
  image: devflow/data:latest
  volumes:
    - /mysql_data:/var/lib/mysql
database:
  image: devflow/database:latest
  env_file:
    # relative to the path where docker-compose.yml is
    - "../database/config/settings.env"
  volumes_from:
    - data
  environment:
    - MYSQL_ROOT_PASSWORD=root
  ports:
    - "3306:3306"